### ISSUE TITLE
Centralize the development workflow here

### ISSUE THREAD

**Issue by vkottler** [vkottler/workspace#8]
We're starting to get `workspace` set up as a place to develop from.

We need to finish the initial "pull" script that will try to pull `master` for the module and their `config` submodules (and fix the URL).

We also may want to just `checkout master` if anything is in a detached-HEAD state.

Once that's working, we can start running `mk` commands in each project using `multiprocessing.Pool`.

Potentially we could automate updating and committing things (like simple regenerations).

**Comment by vkottler** [comment]
Workflow for pulling `config`, `dz-sync`, if changes then branch, commit, push and open pull request (we have done this already)

**Comment by vkottler** [comment]
That workflow should always update `datazen`, too. We could make a different script that's there just to update packages

**Comment by vkottler** [comment]
We need to fix package building and remove vmklib as a dependency, probably we should just make a new package that can be used as a build shim and take over vmklib/setup.py

**Comment by vkottler** [comment]
Okay... we now have (and are using) https://github.com/vkottler/setuptools-wrapper

Now we can do the code documentation-generation thing? Then continue work on vcorelib?

**Comment by vkottler** [comment]
Generating docs should be a script in this repository, probably

**Comment by vkottler** [comment]
would be nice to switch away from syntastic in vim, doesn't have a TOML syntax checker

**Comment by vkottler** [comment]
https://github.com/vkottler/workspace/issues/8#issuecomment-1091394295

it's time to do this now that we significantly upgraded `vcorelib`. "scripts" in the workspace can now more easily encode/decode data

**Comment by vkottler** [comment]
hit a snag trying to generate docs:

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vkottler/Documents/git/workspace/vcorelib/logging.html' -> '/home/vkottler/Documents/git/workspace/vkottler.github.io/python/pydoc/vcorelib/logging.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/vkottler/Documents/git/workspace/scripts/package_pydoc.py", line 63, in repo_entry
    move(str(source_html), str(dest_html))
  File "/usr/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vkottler/Documents/git/workspace/vcorelib/logging.html'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vkottler/Documents/git/workspace/scripts/package_pydoc.py", line 78, in <module>
    sys.exit(main())
  File "/home/vkottler/Documents/git/workspace/scripts/package_pydoc.py", line 72, in main
    pool.map(repo_entry, get_python_submodules(Path.cwd()))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/home/vkottler/Documents/git/workspace/vcorelib/logging.html'
make: *** [/tmp/tmpf_3sr009:38: py-script-package_pydoc] Error 1
make: Leaving directory '/home/vkottler/Documents/git/workspace'
```

**Comment by vkottler** [comment]
We fixed the above but unfortunately our strategy has a problem. The `__init__.py` module's generated outputs don't show the other modules in that directory

**Comment by vkottler** [comment]
I think we can fix it. Instead of targeting `__init__.py` we need to target the parent directory

**Comment by vkottler** [comment]
Success! https://vkottler.github.io/python/pydoc/

**Comment by vkottler** [comment]
We can now link individual Python projects' README headers to stable links. That's the next step
